### ISSUE TITLE
Unwanted collider in the text asset and glb

### ISSUE THREAD

**Issue by akash14darshan** [AfterNow/ANPrezSDK#27]
We should remove all kinds of Collider like box/mesh/sphere colliders from glb and assetbundle after loading
Unwanted colliders can block the user's raycast which may cause problems for them.

Text asset also has a collider which can just be deleted from the prefab itself

**Comment by whoisvinod** [comment]
Removing colliders entirely is not a supposed solution because we need colliders for assets which are marked as "interactable" in web portal. Also we are using colliders for glb re-scaling. This can be tackled by following 2 steps:

1. Check if an asset is marked as interactable and only add colliders for that asset.

2. After re-scaling delete colliders on glb models


T:{07.30}

**Comment by whoisvinod** [comment]
Fixed the issue and created PR [#34](https://github.com/AfterNow/ANPrezSDK/pull/34) for same.

T{04:00}
